/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as ReportesIndexRouteImport } from './routes/reportes/index'
import { Route as MembershipsIndexRouteImport } from './routes/memberships/index'
import { Route as InventarioIndexRouteImport } from './routes/inventario/index'
import { Route as InstructorsIndexRouteImport } from './routes/instructors/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as CajaIndexRouteImport } from './routes/caja/index'
import { Route as StudentsStudentIdIndexRouteImport } from './routes/students/$studentId/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIndexRoute = ReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsIndexRoute = MembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIndexRoute = InventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsIndexRoute = InstructorsIndexRouteImport.update({
  id: '/instructors/',
  path: '/instructors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaIndexRoute = CajaIndexRouteImport.update({
  id: '/caja/',
  path: '/caja/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdIndexRoute = StudentsStudentIdIndexRouteImport.update({
  id: '/students/$studentId/',
  path: '/students/$studentId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/caja/': typeof CajaIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/instructors/': typeof InstructorsIndexRoute
  '/inventario/': typeof InventarioIndexRoute
  '/memberships/': typeof MembershipsIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/students/$studentId/': typeof StudentsStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/caja': typeof CajaIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/instructors': typeof InstructorsIndexRoute
  '/inventario': typeof InventarioIndexRoute
  '/memberships': typeof MembershipsIndexRoute
  '/reportes': typeof ReportesIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/students/$studentId': typeof StudentsStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/caja/': typeof CajaIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/instructors/': typeof InstructorsIndexRoute
  '/inventario/': typeof InventarioIndexRoute
  '/memberships/': typeof MembershipsIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/students/$studentId/': typeof StudentsStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/login'
    | '/settings'
    | '/caja/'
    | '/classes/'
    | '/instructors/'
    | '/inventario/'
    | '/memberships/'
    | '/reportes/'
    | '/reservations/'
    | '/students/'
    | '/students/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/login'
    | '/settings'
    | '/caja'
    | '/classes'
    | '/instructors'
    | '/inventario'
    | '/memberships'
    | '/reportes'
    | '/reservations'
    | '/students'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/login'
    | '/settings'
    | '/caja/'
    | '/classes/'
    | '/instructors/'
    | '/inventario/'
    | '/memberships/'
    | '/reportes/'
    | '/reservations/'
    | '/students/'
    | '/students/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CajaIndexRoute: typeof CajaIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  InstructorsIndexRoute: typeof InstructorsIndexRoute
  InventarioIndexRoute: typeof InventarioIndexRoute
  MembershipsIndexRoute: typeof MembershipsIndexRoute
  ReportesIndexRoute: typeof ReportesIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  StudentsStudentIdIndexRoute: typeof StudentsStudentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/': {
      id: '/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ReportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships/': {
      id: '/memberships/'
      path: '/memberships'
      fullPath: '/memberships/'
      preLoaderRoute: typeof MembershipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/': {
      id: '/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof InventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors/': {
      id: '/instructors/'
      path: '/instructors'
      fullPath: '/instructors/'
      preLoaderRoute: typeof InstructorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja/': {
      id: '/caja/'
      path: '/caja'
      fullPath: '/caja/'
      preLoaderRoute: typeof CajaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/': {
      id: '/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/students/$studentId/'
      preLoaderRoute: typeof StudentsStudentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CajaIndexRoute: CajaIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  InstructorsIndexRoute: InstructorsIndexRoute,
  InventarioIndexRoute: InventarioIndexRoute,
  MembershipsIndexRoute: MembershipsIndexRoute,
  ReportesIndexRoute: ReportesIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  StudentsStudentIdIndexRoute: StudentsStudentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
