/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is AUTO-GENERATED by TanStack Router's Vite plugin.
// Do NOT edit manually. Run `pnpm dev` to regenerate.
// See: https://tanstack.com/router/latest/docs/framework/react/routing/file-based-routing

export const routeTree = {} as any;
